apiVersion: containerservice.azure.com/v20251002preview
kind: MaintenanceConfiguration
metadata:
  name: aksmanagedautoupgradeschedule
  namespace: default
spec:
  owner:
    name: sample-managedcluster-20251002preview
  maintenanceWindow:
    schedule:
      weekly:
        dayOfWeek: Saturday
        intervalWeeks: 1
    durationHours: 12
    startTime: 00:00
