name: Publish helm charts
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref or full SHA of commit to generate Helm chart for'
        required: true
        default: 'main'
  # run when a release is published,
  # which creates a new tag
  push:
    tags:
      - v2*

env:
  ref: "${{ github.event.inputs.ref || github.ref_name }}"

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    # Only run this scheduled job on the main repo, it can't work elsewhere
    if: ${{ github.repository == 'Azure/azure-service-operator' }}

    steps:
      - name: Create token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ secrets.AUTOMATION_ID }}
          private-key: ${{ secrets.AUTOMATION_KEY }}
          
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pinned to 6.0.2
        with:
          ref: ${{ env.ref }}
          fetch-depth: 0 # required to access tags
          submodules: 'true'

      - name: Get SHA
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create Branch
        uses: peterjgrainger/action-create-branch@10c7d268152480ae859347db45dc69086cef1d9c # pinned to v3.0.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          branch: ${{ format('bot/update-helm-chart-{0}', env.ref) }}
          sha: ${{ env.sha }}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pinned to 6.0.2
        with:
          ref: ${{ format('bot/update-helm-chart-{0}', env.ref) }}
          fetch-depth: 0 # required to access tags
          submodules: 'true'

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # pinned to v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devcontainer image
        run: |
          docker build --cache-from ghcr.io/azure/azure-service-operator/aso-devcontainer:latest --tag devcontainer:latest .devcontainer
        env:
          DOCKER_BUILDKIT: 1

      - name: Run devcontainer image
        id: devcontainer
        run: |
          container_id=$(docker create -w /workspace -v $GITHUB_WORKSPACE:/workspace -v /var/run/docker.sock:/var/run/docker.sock devcontainer:latest)
          docker start "$container_id"
          echo "container_id=$container_id" >> $GITHUB_ENV

      - name: Generate helm manifest
        run: |
          container_id=${{ env.container_id }}
          docker exec "$container_id" task controller:package-helm-manifest

      # Workaround for getting "Permission denied" errors when trying to stage files
      - name: Take Ownership
        run: sudo chown -R $USER:$USER .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # pinned to v7.0.11
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: Add Helm Chart
          branch: ${{ format('bot/update-helm-chart-{0}', env.ref) }}
          base: main
          delete-branch: true
          title: "[Automated] Add Helm Chart"
          body: |
            Add new helm chart for latest release

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr
